/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-west-2",
    "aws_user_pools_web_client_id": "31i4f4k9uqujnsl6o4aumcvlgu",
    "api_base_url": "https://l1unaseofh.execute-api.us-west-2.amazonaws.com/prod",
    "cognito_hosted_domain": "mytodoappdemo-todo-demo.auth.us-west-2.amazoncognito.com",
    // "redirect_url": "https://master.d1gbbx9nzhqa8j.amplifyapp.com"
    "redirect_url": "http://localhost:8000"

};

export default awsconfig;
