/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-west-2",
    "aws_user_pools_web_client_id": "7rnoja5sv5i2ifq6khuujfhs5k",
    "api_base_url": "https://nu1vvuyxc1.execute-api.us-west-2.amazonaws.com/prod",
    "cognito_hosted_domain": "thermostatdemo-thermostat-demo.auth.us-west-2.amazoncognito.com",
    "redirect_url": "https://master.d1cr5ovm4o4uz7.amplifyapp.com"
};

export default awsconfig;
