/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "ap-northeast-1",
    "aws_user_pools_web_client_id": "74htfie9v42vbolqbidambks0b",
    "api_base_url": "https://tke8ippabe.execute-api.ap-northeast-1.amazonaws.com/prod",
    "cognito_hosted_domain": "thermostatdemo-serverless-thermostat.auth.ap-northeast-1.amazoncognito.com",
    "redirect_url": "https://master.d1emtm742mw6mp.amplifyapp.com"
};

export default awsconfig;
